title: M de Mates
description: Hola
theme: just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark
color: red

a:link {
  color: red;
}



logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/icon.png"

math: katex
  
callouts:
  nota:
    title: Nota
    color: red

