title: M de Mates
description: Hola
theme: just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark


a:link {
  colors: "#FF0000"
}



logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/icon.png"

math: katex
  
callouts:
  nota:
    title: Nota
    color: red

